[package]
name = "rust_browser"
version = "0.1.0"
edition = "2024"

[dependencies]
thirtyfour = { version = "0.36.1", features = ["tokio-multi-threaded"] }
tokio = { version = "1.48.0", features = ["full"] }
